Repository falconArdente/diploma-team_4-koh_11-practicum-android, pull requests merged in 2024-07, with the labels that each got.

#63 27 Работа с базой данных
  .gitignore
  app/src/main/java/ru/practicum/android/diploma/db/data/db/AppDatabase.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/VacancyDao.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/VacancyDbConvertor.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/AreaEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/BrandSnippetEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/ContactsEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/ContactsJoinPhone.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/CurrencyEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/EmployerEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/EmployerJoins.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/ExperienceEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/IndustryEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/IndustryJoinSphereEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/IndustrySphereEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/JobInfoEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/JobInfoJoins.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/LogosEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/PhoneEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/SalaryEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/SalaryJoinCurrency.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/SkillsEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/VacancyEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/VacancyInfoEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/VacancyJoins.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/impl/VacancyRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/db/domain/api/VacancyRepository.kt
  app/src/main/java/ru/practicum/android/diploma/details/domain/api/DetailsDbInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/details/domain/impl/DetailsDbInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
  app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
  app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/api/FavoriteDbInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/impl/FavoriteDbInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/search/ui/SearchJobFragment.kt
Labels: Ожидает проверки

#62 35 Реализовать логику получения данных для наполнения UI избранного
  app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
  app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
  app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/data/repository/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/favorites/data/repository/FavoritesRepositoryRoomBased.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/api/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/api/GetFavoritesListUseCase.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/impl/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/impl/GetFavoritesListImpl.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/impl/LocalRepository.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/domain/model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/favorites/presentation/state/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/favorites/presentation/state/FavoritesListState.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/presentation/viewmodel/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/favorites/presentation/viewmodel/FavoritesViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/ui/FavoritesJobsFragment.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/ui/VacancyDetailsRecyclerAdapter.kt
  app/src/main/java/ru/practicum/android/diploma/favorites/ui/VacancyDetailsViewHolder.kt
  app/src/main/java/ru/practicum/android/diploma/utils/Mok.kt
  app/src/main/java/ru/practicum/android/diploma/utils/PixelToDp.kt
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/dimens.xml
Labels: Ожидает проверки

#92 40. Mok и модель региона для запроса региона
  app/src/main/java/ru/practicum/android/diploma/filter/domain/model/Area.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/model/Country.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/model/Industry.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/model/SphereOfIndustry.kt
  app/src/main/java/ru/practicum/android/diploma/utils/Mok.kt
Labels: Ожидает проверки

#116 44 Настройка работы фильтров (Отрасль, Общий фильтр)
  app/src/main/java/ru/practicum/android/diploma/db/data/db/AppDatabase.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/VacancyDao.kt
  app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
  app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
  app/src/main/java/ru/practicum/android/diploma/filter/data/mapper/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/filter/data/repository/FilterStorageRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/filter/data/storage/SharedPrefsStorage.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/api/FilterDictionariesInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/api/FilterStorageInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/impl/FilterDictionariesInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/impl/FilterStorageInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/impl/FilterStorageRepository.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/model/.gitkeep
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/model/IndustryWithCheck.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/state/FilterIndustryState.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/state/FilterSettingsState.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/FilterIndustryViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/FilterSettingsViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterIndustryAdapter.kt
  app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterIndustryFragment.kt
  app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterSettingsFragment.kt
  app/src/main/java/ru/practicum/android/diploma/search/ui/SearchJobFragment.kt
  app/src/main/res/values/strings.xml
Labels: Ожидает проверки

#120 Поправил обработку сетевых событий в старых функциях
  app/src/main/java/ru/practicum/android/diploma/filter/data/repository/FilterDictionariesRepositoryHHNetworkClientBased.kt
Labels: Ожидает проверки, bugFix

#125 46 Сцепил фильтры с параметризованным поиском
  app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
  app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/mapper/SearchVacancyConverter.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/repository/GetFilterUseCaseImpl.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/search/domain/api/GetFilterUseCase.kt
  app/src/main/java/ru/practicum/android/diploma/search/domain/api/SearchInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/search/domain/model/SearchParameters.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/state/SearchFragmentState.kt
  app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/search/ui/SearchJobFragment.kt
Labels: Ожидает проверки

#150 56 bugfix
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/AreaEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/EmployerEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/JobInfoEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/LogosEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/SalaryEntity.kt
  app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/VacancyEntity.kt
  app/src/main/java/ru/practicum/android/diploma/details/presentation/JobDetailsFragment.kt
  app/src/main/java/ru/practicum/android/diploma/details/presentation/state/VacancyDetailsState.kt
  app/src/main/java/ru/practicum/android/diploma/details/presentation/viewmodel/VacancyDetailsViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/filter/data/repository/FilterStorageRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/api/FilterStorageInteractor.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/impl/FilterStorageInteractorImpl.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/impl/FilterStorageRepository.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterIndustryFragment.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterSettingsFragment.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/state/FilterIndustryState.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/state/FilterSettingsState.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/FilterIndustryViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/FilterSettingsViewModel.kt
  app/src/main/res/layout/fragment_filter_settings.xml
Labels: bugFix

#182 Знак загрузки при начале поиска, а не при начале debonce отсчета
  app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt
Labels: bugFix

#196 Исправлены баги с фильтром (чекбокс)
  app/src/main/java/ru/practicum/android/diploma/filter/data/repository/FilterStorageRepositoryImpl.kt
  app/src/main/java/ru/practicum/android/diploma/filter/domain/model/FilterGeneral.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterSettingsFragment.kt
  app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/FilterSettingsViewModel.kt
  app/src/main/java/ru/practicum/android/diploma/search/data/mapper/SearchVacancyConverter.kt
Labels: Ожидает проверки, bugFix
